import { ReactNode } from 'react'
import type { Metadata } from 'next';
import '@/styles/global.css.ts';
import { resolveTheme } from '@/themes'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface LayoutParams {
    params: Promise<{
        brand: string;
    }>;
    children: ReactNode;
}

export default async function BrandLayout({
    children,
    params
}: LayoutParams) {
    const resolvedParams = await params;
    const themeClass = resolveTheme(resolvedParams.brand);

    return (
        <html lang="en">
            <body className={themeClass}>
                <Header brand={resolvedParams.brand} />
                {children}
                <Footer brand={resolvedParams.brand} />
            </body>
        </html>
    );
}
